apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sensorgateways.iot.unnop.dev
spec:
  group: iot.unnop.dev
  scope: Namespaced
  names:
    kind: SensorGateway
    plural: sensorgateways
    singular: sensorgateway
    shortNames: [sg]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [site, protocol, alertProfile]
              properties:
                site: { type: string }
                protocol:
                  type: string
                  enum: [modbus-tcp, mqtt, opc-ua]
                sampleIntervalSeconds:
                  type: integer
                  minimum: 1
                  default: 5
                alertProfile:
                  type: string
                  enum: [gas-detection, cems, water-quality]
            status:
              type: object
              properties:
                ready: { type: boolean }
                lastSeen: { type: string }
      additionalPrinterColumns:
        - name: Site
          type: string
          jsonPath: .spec.site
        - name: Profile
          type: string
          jsonPath: .spec.alertProfile
        - name: Ready
          type: boolean
          jsonPath: .status.ready
