apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-service
        image: ghcr.io/thefuriousowl/iot-ingestion-service:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_EXTRA_CA_CERTS
          value: "/app/rds-ca-bundle.pem"
        - name: DATABASE_URL
          value: "postgresql://iotadmin:TempPass123Dev@iot-dev-timescale.cbs6g4ccs1gt.eu-west-1.rds.amazonaws.com:5432/iot_telemetry?schema=public&sslmode=require"
        - name: MQTT_BROKER_URL
          value: "mqtt://mosquitto.iot.svc.cluster.local:1883"
        - name: REDIS_HOST
          value: "redis.iot.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: iot
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: ingestion-service
